### ISSUE TITLE
Build on windows

### ISSUE THREAD

**Issue by MukilanP** [SoftwareVerde/java-dukpt#1]
Hi,

Thanks for the code.

Can you please let us know the build steps?. I installed gradle and ran the gradlew.bat and build.gradle. I didn't get the output library.

Regards,
Mukilan

**Comment by thesquaregroot** [comment]
Hi @MukilanP 

Can you share the output of running the gradlew script?

On a Unix system at least running `gradlew build` should work, so I would assume `gradlew.bat build` would be sufficient on Windows.  We do have the custom command `makeJar` that you can try running if that doesn't work: `gradlew.bat makeJar`.

For me the jar is built to `build/libs/java-dukpt-1.0.0.jar`.  After building can you check for the jar there?

**Comment by joshmg** [comment]
@MukilanP - I believe you can also use [git-bash](https://gitforwindows.org/) to run the `scripts/make-jar.sh` script in the project root, which will put the jar file in `out/bin/`.

@thesquaregroot 's suggestions should also work on windows: `gradlew.bat makeJar`

Let us know how it goes.

**Comment by thesquaregroot** [comment]
Since we haven't heard back on this we're assuming you either got things working or otherwise don't need any further assistance.  If you are still experiencing this issue let us know what you've tried since posting and we'll take a closer look.
